// 20200213/vue-app/src/components/TodoList.vue
<template>
  <ul v-if="items.length">
    <li v-for="item in items" :key="item.id">
      {{ item.text }}
    </li>
  </ul>
  <p v-else>No items found.</p>
</template>

<script>
export default {
  name: 'TodoList',
  props: ['items']
}
</script>

<style scoped>
ul {
  background: aliceblue;
  list-style: upper-roman;
}
</style>

// 20200213/react-app/src/components/TodoList.jsx
import React from 'react'

import classes from './TodoList.module.css'

const TodoList = props => {
  const items = props.items
  if (items.length < 0) {
    return <p>No items found.</p>
  }

  return (
    <ul className={classes.items}>
      {items.map(item => (
        <li key={item.id}>{item.text}</li>
      ))}
    </ul>
  )
}

// // const TodoList = function TodoList(props) {
// const TodoList = props => {
//   const items = props.items

//   return (
//     <>
//       {0 < items.length ? (
//         <ul>
//           {items.map(item => (
//             <li key={item.id}>{item.text}</li>
//           ))}
//         </ul>
//       ) : (
//         <p>No items found.</p>
//       )}
//     </>
//   )
// }

export default TodoList
